name: dms-vep-pipeline-3

channels:
  - conda-forge
  - bioconda

dependencies:
  - altair=5.4
  - biopython=1.83
  - black-jupyter
  - entrez-direct=16.2
  - flatdict=4.0
  - git-lfs
  - jupyterlab
  - mafft=7.525
  - markdown=3.4
  - matplotlib=3.8
  - minimap2=2.26
  - nbstripout
  - numpy<2  # pinned due to this issue: https://github.com/nteract/papermill/issues/800
  - openpyxl
  - pandas=2.2
  - papermill=2.6
  - pip
  - plotnine=0.12
  - pyarrow
  - python=3.11
  - ruamel.yaml=0.17
  - ruff
  - seaborn=0.13
  - snakefmt
  - snakemake=8.20.6
  - upsetplot=0.9
  - pip:
      - alignparse==0.6.2
      - baltic==0.2.2
      - dms_variants==1.4.3
      - dmslogo==0.7.0
      - multidms==0.3.3
      - neutcurve==2.1
      - polyclonal==6.12
